version: '3'
services:
  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=notification
      - POSTGRES_USER=notification
      - POSTGRES_PASSWORD=notification
    volumes:
      - /var/lib/postgresql/data